spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todosdb?serverTimeZone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database: mysql
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: debug